#   .-.-. .-.-. .-.-. .-.-. .-.-. .-.-. .-.-. .-.-. .-.-. .-.-.
#   ( L .'( i .'( f .'( e .'( S .'( t .'( o .'( l .'( e .'( n .'
#    `.(   `.(   `.(   `.(   `.(   `.(   `.(   `.(   `.(   `.(
#
# Plugin by KadotCom

# General

disableVersionMessage: false # Indicates whether the version message should be enabled.

HP:
  startHP: 20 # When a player first joins a server, the health will be set to this.
  returnHP: 20 #  When a player is unbanned, their health will reset
  maxHP: 120 # HP that when reached, the player will not gain anymore health

death:
  banOnDeath: true # If set to true, the player will be banned when they lose all their hearts. If set to false, the player will be put in spectator instead.
  teleportOnDeath: false # If set to true, the player will be teleported on death. If set to false, the player won't be teleported on death. (Overrides banOnDeath)
  anyDeathRemovesHearts: true # If set false the player will only lose hearts if another player kills them.
  fullDeathAnnouncement: "&4${player} ran out of hearts..." # The message that appears when player loses all their hearts - ${player} = Player who died.
  clearItemsOnFullDeath: false # When a player dies and get banned, all the players items will be cleared. Only if banOnDeath is true.
  dropHeartOnDeath: false # Heart Item drops when a player dies from a player (if anyDeathRemovesHearts is false) or by anything (if anyDeathRemovesHearts is true)
  runCommandsOnDeath: false # If set to true, command(s) will run when a full death occurs.

# Permissions

permissions:
  # bePermissionBased - Indicates whether a command should be permission based, or not.
  # permission - Indicates what permission the player needs to run the command.
  vercheck:
    bePermissionBased: false
    permission: "lifestolen.vercheck"
  health:
    bePermissionBased: false
    permission: "lifestolen.health"
  withdraw:
    bePermissionBased: false
    permission: "lifestolen.withdraw"
  lshelp:
    bePermissionBased: false
    permission: "lifestolen.lshelp"
  viewrecipes:
    bePermissionBased: false
    permission: "lifestolen.viewrecipes"
  viewusage:
    bePermissionBased: false
    permission: "lifestolen.viewusage"
  messages:
    outdatedPermissionMessage: "lifestolen.message.outdated"
  permissionToDoEverything: "lifestolen.*" # The permission someone needs to run all permission based commands.

# Item
# To see valid items, go to this website 'https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html'

heart:
  itemName: "Heart" # Item name.
  itemLore: "This will give you one heart." # Item lore.
  isEnabled: true # Indicates if an item is enabled or disabled.
  disabledMessage: '&cThe heart item is disabled on this server.' # Message that appears if this item is disabled
  item: 'RED_DYE' # Item used for hearts
  haveLimitedUses: false # When this is enabled, you can use this item a certain amount of times before you can't use this item anymore.
  uses: 5 # Uses that are allowed if haveLimitedUses is true.
  useCustomModelData: false # When this is enabled, you can make it so you can set a custom model for this item.
  customModelDataID: 1 # This is where you put your custom model data ID to set the custom model for this item.
  isCraftable: true # If enabled, the item can be crafted.
reviver:
  itemName: "Reviver" # Item name.
  itemLore: "This will revive someone." # Item lore.
  isEnabled: true # Indicates if an item is enabled or disabled.
  disabledMessage: '&cThe reviver item is disabled on this server.' # Message that appears if this item is disabled
  item: 'BEACON' # Item used for revivers
  haveLimitedUses: false # When this is enabled, you can use this item a certain amount of times before you can't use this item anymore.
  uses: 5 # Uses that are allowed if haveLimitedUses is true.
  useCustomModelData: false # When this is enabled, you can make it so you can set a custom model for this item.
  customModelDataID: 1 # This is where you put your custom model data ID to set the custom model for this item.
  isCraftable: true # If enabled, the item can be crafted.

# Death Punishments

banning: # Category for banning a player on full death (if banOnDeath is enabled).
  banTime: 86400 # Ban duration in seconds.
  permBan: false # Will override the ban time and permanently ban the player.
  banReason: "&4You ran out of hearts." # The ban message.
  kickMessage: "&4You ran out of hearts..." # Kick message for when you get banned.

teleporting: # Category for teleporting a player on full death (if teleportOnDeath is enabled).
  xCord: 0.0 # X cord of location you want player to be teleported to
  yCord: 0.0 # Y cord of location you want player to be teleported to
  zCord: 0.0 # Z cord of location you want player to be teleported to
  gamemode: 3 # Gamemode you want the player to be in once being teleported
  # 0 = Survival
  # 1 = Creative
  # 2 = Adventure
  # 3 = Spectator
  giveDefaultHP: true # If enabled, the player will be given the default HP once teleported.

commands: # Category for running commands when a player gets a full death (if runCommandsOnDeath is enabled).
  commandsToRun: ["say Hello.","say World!"] # The commands that will run on full death. (Do not include the / at the beginning.)

# Crafting
# For reference. See this image to see each slots 'https://wiki.vg/images/7/7b/CraftingTable-slots.png' and this for material types 'https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html'
# To make a blank spot, type 'AIR' in one of the slots
# If you want to use the Heart item as an item in the Reviver recipe, type 'HEART' in one of the slots in the ReviverRecipe config.
HeartRecipe:
  Slot1: "REDSTONE_BLOCK"
  Slot2: "REDSTONE_BLOCK"
  Slot3: "REDSTONE_BLOCK"
  Slot4: "REDSTONE_BLOCK"
  Slot5: "GOLDEN_APPLE"
  Slot6: "REDSTONE_BLOCK"
  Slot7: "BONE_MEAL"
  Slot8: "REDSTONE_BLOCK"
  Slot9: "BONE_MEAL"
ReviverRecipe:
  Slot1: "DIAMOND_BLOCK"
  Slot2: "DIAMOND_BLOCK"
  Slot3: "DIAMOND_BLOCK"
  Slot4: "OBSIDIAN"
  Slot5: "TOTEM_OF_UNDYING"
  Slot6: "OBSIDIAN"
  Slot7: "OBSIDIAN"
  Slot8: "OBSIDIAN"
  Slot9: "OBSIDIAN"

# Translations
translation:
  serverName: "LifeStolen" # Name of your server, will be used in GUIs and messages.
  ingameMessages: # Messages that appears with the plugin.
    resetHealth: "Your health has been reset to default." # The message that appears when a players health is reset to the starting HP.
  deathMessages: # Messages that appears when a player dies.
    generic: "${player} was slain by ${attacker}" # The message that appears when a player dies from a generic reason
    explosion: "${player} was exploded by ${attacker}" # The message that appears when a player dies from a explosion
    shot: "${player} was shot by ${attacker}" # The message that appears when a player dies from someone shooting the player.
  errorMessages: # The message that appears when a player encounters an error when running a command.
    noPermission: "You don't have permission to use this command." # The message that appears when a player doesn't have permission to use a command.
    offlinePlayer: "Player wasn't found." # The message that appears when an offline player is mentioned in a command.
    itemDoesNotExist: "This item does not exist in LifeStolen plugin." # The message that appears when an item is mentioned that doesn't exist with the plugin
    amountUnderZero: "Please specify a value over 0" # The message that appears when a number is given that is under, or is zero.
    amountOverSixtyFour: "Please specify a value under 64" # The message that appears when a number is given that is over 64
    missingArguments: "You are missing arguments in the command." # The message that appears when you don't give enough arguments in a command.